//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetVS2017.Capitulo08.EF.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoImagem
    {
        public int Produto_Id { get; set; }
        public byte[] Imagem { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
